### ISSUE TITLE
Failed to parse: meta for dependencies because of FatalException

### ISSUE THREAD

**Issue by crtl** [icapps/flutter-icapps-license#34]
Running `fvm flutter packages pub run license_generator check --verbose` returns the following result:

```
[  +58 ms] executing: [C:\Users\User\fvm\versions\2.5.1/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +404 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] executing: [C:\Users\User\fvm\versions\2.5.1/] git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[  +37 ms] Exit code 0 from: git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] 2.5.1
[   +6 ms] executing: [C:\Users\User\fvm\versions\2.5.1/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\User\fvm\versions\2.5.1/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +80 ms] executing: [C:\Users\User\fvm\versions\2.5.1/] git rev-parse --abbrev-ref HEAD
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +62 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +39 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +25 ms] executing: C:\Users\User\fvm\versions\2.5.1\bin\cache\dart-sdk\bin\pub run license_generator check --verbose
Failed to parse: meta for dependencies because of FatalException: with messsage: `Null (dependencies) is no String or YamlMap`
Failed to complete the license generator, because of FatalException: with messsage: `Null (dependencies) is no String or YamlMap`
[ +836 ms] "flutter pub" took 936ms.
[  +34 ms] ensureAnalyticsSent: 31ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

pubspec.yaml
```yaml
version: 1.0.35+40
publish_to: "none"
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: 2.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  algolia: ^1.0.4
  after_init:
    git:
      url: https://github.com/rafaelmaeuer/after_init.git
      ref: master

  sign_in_with_apple: ^3.3.0
  cached_network_image: ^3.2.0
  country_icons: ^2.0.2
  country_pickers: ^2.0.0
  crypto: ^3.0.1

  devicelocale: ^0.5.0
  dio: ^4.0.4
  dio_http2_adapter: ^2.0.0

  enum_to_string: ^2.0.1
  expandable: ^5.0.1
  sliding_up_panel: ^2.0.0+1

  email_validator: ^2.0.1
  event_bus: ^2.0.0

  #
  # Firebase dependencies
  #
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_dynamic_links: ^4.0.4
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  cloud_firestore: ^3.1.6
  cloud_functions: ^3.2.5

  flare_flutter: ^3.0.2
  flutter_local_notifications: ^9.2.0
  flutter_signin_button: ^2.0.0
  flutter_parsed_text: ^2.2.1
  file_picker: ^4.3.2
  flutter_facebook_auth: ^4.0.1
  flutter_staggered_grid_view: ^0.4.1
  facebook_app_events: ^0.14.8
  font_awesome_flutter: ^9.2.0
  another_flushbar: ^1.10.28

  google_sign_in: ^5.2.3

  intl: 0.17.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1


  language_picker:
    git:
      url: https://github.com/adam-podkowinski/flutter_language_pickers.git
      ref: master


  meta:

  package_info: ^2.0.2
  path_provider: ^2.0.8
  path:
  provider: ^6.0.2
  preload_page_view: ^0.1.6

  rxdart: ^0.27.3

  scroll_snap_list: ^0.8.4
  share: ^2.0.4
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2

  table_calendar: ^3.0.3
  oktoast: ^3.1.5

  simple_animations: ^4.0.1
  uuid: ^3.0.5
  url_launcher: ^6.0.18

  video_compress: ^3.1.0
  video_player: ^2.2.13
  video_thumbnail: ^0.4.3

  wakelock: ^0.6.1
  perfect_volume_control: ^1.0.5
  get_it: ^7.2.0
  collection: ^1.15.0-nullsafety.4

  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  visibility_detector: ^0.2.2
  firebase_app_check: ^0.0.6+4

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.1.5
  license_generator: ^1.0.3
  mockito:
  freezed:

license_generator:
  fail_fast: false
  nullsafety: true
```

I am using FVM with Flutter 2.5
```
fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

• No issues found!
```
