### ISSUE TITLE
Add the option to skip specific packages

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-icapps-license#37]
```
license_generator:
  skip_licenses:
      package_x: true
      package_x: false
```
